services:
  - type: web
    name: green-quest
    runtime: node
    region: oregon
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: npm start
    releaseCommand: cd server && npx prisma migrate deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: green-quest-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: green-quest-db
    databaseName: green_quest
    plan: free
    region: oregon
